@startuml
actor Secretaria as user
participant VistaRegistroEst as view
participant EstudianteController as controller
participant EstudianteDB as db
participant EstudianteModel as model
participant "Sesión" as session

user -> view: Llena formulario \nregistro estudiante
user -> view: Click "Registrar Estudiante"

view -> controller: ejecuta POST registrarEstudiante()

controller -> session: Obtener idUsuario de sesión
session --> controller: retorna idUsuario

controller -> model:crea new EstudianteModel(datos, idUsuario)
controller -> db: crear(EstudianteModel)

db -> db: Ejecuta INSERT SQL\ncon usuario_id
db --> controller: boolean (éxito/fracaso)

alt Registro exitoso
    controller --> view: Redirecciona con éxito\nHTTP 302
else Error en registro
    controller --> view: Redirecciona con error\nHTTP 302
end

view --> user: Muestra resultado
@enduml